### ISSUE TITLE
Navigation title

### ISSUE THREAD

**Issue by xinemata** [burnedsap/web-accessibility#2]
There is a ```<p>``` tag inside ```<nav>``` which seems to indicate the title of the nav bar. Is this a standard way of approaching titling the nav bar?

```
<nav>
    <p>
      Projects created in Fall 2020
    </p>
    <ul>
      <li>
        <a href="p1.html"> Coffee Cup Generator
        </a>
      </li>
      <li>
        <a href="p2.html"> Coming Soon
        </a>
      </li>
    </ul>
  </nav>
```

**Comment by burnedsap** [comment]
That's a good question! I'll look it up.

**Comment by burnedsap** [comment]
I've changed the `<p>` tag to `<h5>` tag to indicate a heading within the nav. https://github.com/burnedsap/web-accessibility/commit/3a4c59aaec9ef24dd0557b8ccee2236e210e9274
